/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var d=Object.defineProperty;var h=Object.getOwnPropertyDescriptor;var m=Object.getOwnPropertyNames;var f=Object.prototype.hasOwnProperty;var u=(n,e)=>{for(var o in e)d(n,o,{get:e[o],enumerable:!0})},w=(n,e,o,i)=>{if(e&&typeof e=="object"||typeof e=="function")for(let t of m(e))!f.call(n,t)&&t!==o&&d(n,t,{get:()=>e[t],enumerable:!(i=h(e,t))||i.enumerable});return n};var b=n=>w(d({},"__esModule",{value:!0}),n);var y={};u(y,{default:()=>l});module.exports=b(y);var g=require("obsidian");function C(n){let e=n.split(`
`),o=e[0].trim(),i={appName:"graphing",width:800,height:600,showToolBar:!1,showAlgebraInput:!1,showMenuBar:!1,enableShiftDragZoom:!0,enableRightClick:!1,capturingThreshold:null};if(o.startsWith("{")&&o.endsWith("}"))try{let t=JSON.parse(o);i={...i,...t},n=e.slice(1).join(`
`)}catch(t){console.error("Invalid configuration in GeoGebra block:",t)}return{ggbAppletOptions:i,commands:n.trim()}}var l=class extends g.Plugin{async onload(){console.log("GeoGebra Plugin loaded!"),this.registerMarkdownCodeBlockProcessor("geogebra",(e,o,i)=>{let{ggbAppletOptions:t,commands:p}=C(e),s=document.createElement("div");s.id="ggbApplet",s.style.width=`${t.width}px`,s.style.height=`${t.height}px`,o.appendChild(s);let a=document.createElement("script");a.src="https://www.geogebra.org/apps/deployggb.js",a.charset="UTF-8",document.head.appendChild(a),a.onload=()=>{let r=new window.GGBApplet(t,!0);r.inject(s.id),r.registerClientListener(()=>{p&&p.split(`
`).filter(c=>c.trim()!=="").forEach(c=>{r.evalCommand(c)})})}})}onunload(){console.log("GeoGebra Plugin unloaded!")}};
